##############################################
# Spark Cluster
##############################################

spark.master                     spark://spark-master:7077
spark.app.name                   BigDataLab

##############################################
# HDFS
##############################################

spark.hadoop.fs.defaultFS         hdfs://namenode:9000

##############################################
# Spark SQL
##############################################

spark.sql.catalogImplementation=hive

hive.metastore.uris=thrift://hive-metastore:9083

spark.sql.warehouse.dir=hdfs://namenode:9000/user/hive/warehouse

spark.eventLog.enabled=true

spark.eventLog.dir=/tmp/spark-events

##############################################
# Event Logs
##############################################

spark.eventLog.enabled            true
spark.eventLog.dir                file:///tmp/spark-events

##############################################
# Serializer
##############################################

spark.serializer                  org.apache.spark.serializer.KryoSerializer

##############################################
# Time Zone
##############################################

spark.sql.session.timeZone        UTC